VQ:
  h_dim: 128
  n_embeddings: 1024
  embedding_dim: 8

LDM:
  in_channels: 3
  out_channels: 3
  model_channels: 128
  attention_resolutions: [1, 2, ]
  num_res_blocks: 2
  dropout: 0.1
  channel_mult: [1, 2, 2, 2]
  conv_resample: True
  num_heads: 4

Transformer:
  n_embeddings: 
