### model params
Model:
  in_channels: 8
  out_channels: 8
  model_channels: 128
  attention_resolutions: [1, 2, ]
  num_res_blocks: 2
  dropout: 0.1
  channel_mult: [1, 2, 2, 2]
  conv_resample: True
  num_heads: 4

### trainer params
Trainer:
  # sample time steps
  T: 1000
  beta: [0.0001, 0.02]
